<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AdeleToAadl" nsURI="platform:/resource/AdeleToAadl/model/AdeleToAadl.ecore"
    nsPrefix="AdeleToAadl">
  <eClassifiers xsi:type="ecore:EClass" name="AdeleTypeToAadlComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Adele/model/Adele.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/Aadl/model/Aadl.ecore#//ComponentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdeleAccessToAadlAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Adele/model/Adele.ecore#//Access"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/Aadl/model/Aadl.ecore#//Access"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdeleFeatureToAadlFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Adele/model/Adele.ecore#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/Aadl/model/Aadl.ecore#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ruleAccessToAcess__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__adeleAccess"
        lowerBound="1" eType="ecore:EClass platform:/resource/Adele/model/Adele.ecore#//Access"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__adeleType"
        lowerBound="1" eType="ecore:EClass platform:/resource/Adele/model/Adele.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__aadlAccess"
        lowerBound="1" eType="ecore:EClass platform:/resource/Aadl/model/Aadl.ecore#//Access"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__aadleType"
        lowerBound="1" eType="ecore:EClass platform:/resource/Aadl/model/Aadl.ecore#//ComponentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__adleTypeToaadlComponent"
        lowerBound="1" eType="ecore:EClass platform:/resource/AdeleToAadl/model/AdeleToAadl.ecore#//AdeleTypeToAadlComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__adleaccessToaadlaccess"
        lowerBound="1" eType="ecore:EClass platform:/resource/AdeleToAadl/model/AdeleToAadl.ecore#//AdeleAccessToAadlAccess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ruleAccessToAcessrefined__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__adeleAccess"
        lowerBound="1" eType="ecore:EClass platform:/resource/Adele/model/Adele.ecore#//Access"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__adeleRefinedFeature"
        lowerBound="1" eType="ecore:EClass platform:/resource/Adele/model/Adele.ecore#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__adeleType"
        lowerBound="1" eType="ecore:EClass platform:/resource/Adele/model/Adele.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__aadlAccess"
        lowerBound="1" eType="ecore:EClass platform:/resource/Aadl/model/Aadl.ecore#//Access"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__aadlRefinedFeature"
        lowerBound="1" eType="ecore:EClass platform:/resource/Aadl/model/Aadl.ecore#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__aadleType"
        lowerBound="1" eType="ecore:EClass platform:/resource/Aadl/model/Aadl.ecore#//ComponentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__a2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdeleToAadl/model/AdeleToAadl.ecore#//AdeleAccessToAadlAccess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__a2c" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdeleToAadl/model/AdeleToAadl.ecore#//AdeleTypeToAadlComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__adelefeaturetofeature"
        lowerBound="1" eType="ecore:EClass platform:/resource/AdeleToAadl/model/AdeleToAadl.ecore#//AdeleFeatureToAadlFeature"/>
  </eClassifiers>
</ecore:EPackage>
