<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="HospitalExample" nsURI="platform:/resource/HospitalExample/model/HospitalExample.ecore"
    nsPrefix="HospitalExample">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TODO: Add documentation for HospitalExample. Hint: You may copy this element in the Ecore editor to add documentation to EClasses, EOperations, ..."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Hospital">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reception" lowerBound="1"
        eType="#//Reception" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staff" ordered="false"
        upperBound="-1" eType="#//Staff" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" upperBound="-1"
        eType="#//Department" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reception">
    <eStructuralFeatures xsi:type="ecore:EReference" name="waits" upperBound="-1"
        eType="#//Patient" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Staff" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staffID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="works" eType="#//Department"
        eOpposite="#//Department/staff"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Doctor" eSuperTypes="#//Staff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="caresfor" upperBound="-1"
        eType="#//Patient" eOpposite="#//Patient/doctor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patientCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nurse" eSuperTypes="#//Staff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible" eType="#//Room"
        eOpposite="#//Room/nurses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" upperBound="-1"
        eType="#//Room" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staff" upperBound="-1"
        eType="#//Staff" eOpposite="#//Staff/works"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxRoomCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Patient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patientID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//Carelevel"
        defaultValueLiteral="PENDING"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doctor" lowerBound="1"
        eType="#//Doctor" eOpposite="#//Doctor/caresfor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1" eType="#//Carelevel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lies" upperBound="-1" eType="#//Patient"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nurses" upperBound="-1"
        eType="#//Nurse" eOpposite="#//Nurse/responsible"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Carelevel">
    <eLiterals name="WEAK"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="STRONG" value="2"/>
    <eLiterals name="PENDING" value="3"/>
  </eClassifiers>
</ecore:EPackage>
