<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AlgorithmToStrategy_MA" nsURI="platform:/resource/AlgorithmToStrategy_MA/model/AlgorithmToStrategy_MA.ecore"
    nsPrefix="AlgorithmToStrategy_MA">
  <eClassifiers xsi:type="ecore:EClass" name="AlgorithmsToStrategiesContainerCorr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Algorithms/model/Algorithms.ecore#//AlgorithmContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/Strategies/model/Strategies.ecore#//StrategyContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgorithmToStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Algorithms/model/Algorithms.ecore#//Algorithm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/Strategies/model/Strategies.ecore#//Strategy"/>
  </eClassifiers>
</ecore:EPackage>
