/*
 * generated by Xtext 2.22.0
 */
package org.emoflon.express.ide;


/**
 * Use this class to register ide components.
 */
public class ExpressIdeModule extends AbstractExpressIdeModule {
}
