<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Class2Doc_MA" nsURI="platform:/resource/Class2Doc_MA/model/Class2Doc_MA.ecore"
    nsPrefix="Class2Doc_MA">
  <eClassifiers xsi:type="ecore:EClass" name="classPackate2Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ClassMultipleInheritanceHierarchy/model/classMultipleInheritanceHierarchy.ecore#//ClassPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/Documents/model/Documents.ecore#//Container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="class2doc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ClassMultipleInheritanceHierarchy/model/classMultipleInheritanceHierarchy.ecore#//Clazz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/Documents/model/Documents.ecore#//Document"/>
  </eClassifiers>
</ecore:EPackage>
