/**
 * generated by Xtext 2.22.0
 */
package org.emoflon.express.express.tests;

import junit.textui.TestRunner;

import org.emoflon.express.express.AliasType;
import org.emoflon.express.express.ExpressFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Alias Type</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class AliasTypeTest extends UserDefinedTypeTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(AliasTypeTest.class);
	}

	/**
	 * Constructs a new Alias Type test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AliasTypeTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Alias Type test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected AliasType getFixture() {
		return (AliasType)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ExpressFactory.eINSTANCE.createAliasType());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //AliasTypeTest
