/**
 * generated by Xtext 2.23.0
 */
package org.emoflon.express.express.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.emoflon.express.express.EnumerationValue;
import org.emoflon.express.express.ExpressFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Enumeration Value</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class EnumerationValueTest extends TestCase {

	/**
	 * The fixture for this Enumeration Value test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationValue fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(EnumerationValueTest.class);
	}

	/**
	 * Constructs a new Enumeration Value test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EnumerationValueTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Enumeration Value test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(EnumerationValue fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Enumeration Value test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationValue getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ExpressFactory.eINSTANCE.createEnumerationValue());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //EnumerationValueTest
