/**
 * generated by Xtext 2.22.0
 */
package org.emoflon.express.express.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.emoflon.express.express.ExpressFactory;
import org.emoflon.express.express.ParameterList;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Parameter List</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ParameterListTest extends TestCase {

	/**
	 * The fixture for this Parameter List test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterList fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ParameterListTest.class);
	}

	/**
	 * Constructs a new Parameter List test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ParameterListTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Parameter List test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(ParameterList fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Parameter List test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterList getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ExpressFactory.eINSTANCE.createParameterList());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ParameterListTest
