/**
 * generated by Xtext 2.23.0
 */
package org.emoflon.express.express.tests;

import junit.textui.TestRunner;

import org.emoflon.express.express.ExpressFactory;
import org.emoflon.express.express.RealAttribute;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Real Attribute</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class RealAttributeTest extends AttributeTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(RealAttributeTest.class);
	}

	/**
	 * Constructs a new Real Attribute test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RealAttributeTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Real Attribute test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected RealAttribute getFixture() {
		return (RealAttribute)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ExpressFactory.eINSTANCE.createRealAttribute());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //RealAttributeTest
