/**
 * generated by Xtext 2.23.0
 */
package org.emoflon.express.express.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.emoflon.express.express.ExpressFactory;
import org.emoflon.express.express.SchemaContainer;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Schema Container</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class SchemaContainerTest extends TestCase {

	/**
	 * The fixture for this Schema Container test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SchemaContainer fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(SchemaContainerTest.class);
	}

	/**
	 * Constructs a new Schema Container test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SchemaContainerTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Schema Container test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(SchemaContainer fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Schema Container test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SchemaContainer getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ExpressFactory.eINSTANCE.createSchemaContainer());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //SchemaContainerTest
