/**
 * generated by Xtext 2.23.0
 */
package org.emoflon.express.express.tests;

import junit.textui.TestRunner;

import org.emoflon.express.express.ExpressFactory;
import org.emoflon.express.express.SelectType;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Select Type</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class SelectTypeTest extends UserDefinedTypeTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(SelectTypeTest.class);
	}

	/**
	 * Constructs a new Select Type test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SelectTypeTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Select Type test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected SelectType getFixture() {
		return (SelectType)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ExpressFactory.eINSTANCE.createSelectType());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //SelectTypeTest
