/**
 * generated by Xtext 2.22.0
 */
package org.emoflon.express.express.tests;

import junit.textui.TestRunner;

import org.emoflon.express.express.ExpressFactory;
import org.emoflon.express.express.UserDefinedTypeReference;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>User Defined Type Reference</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class UserDefinedTypeReferenceTest extends TypeTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(UserDefinedTypeReferenceTest.class);
	}

	/**
	 * Constructs a new User Defined Type Reference test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public UserDefinedTypeReferenceTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this User Defined Type Reference test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected UserDefinedTypeReference getFixture() {
		return (UserDefinedTypeReference)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ExpressFactory.eINSTANCE.createUserDefinedTypeReference());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //UserDefinedTypeReferenceTest
