/*
 * generated by Xtext 2.37.0
 */
package org.emoflon.express.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractExpressScopeProvider extends DelegatingScopeProvider {
}
