<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ConstructionPlan" nsURI="platform:/resource/ConstructionPlan/model/ConstructionPlan.ecore"
    nsPrefix="ConstructionPlan">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TODO: Add documentation for ConstructionPlan. Hint: You may copy this element in the Ecore editor to add documentation to EClasses, EOperations, ..."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PlanCollection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plans" upperBound="-1"
        eType="#//Plan" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constructions" upperBound="-1"
        eType="#//Construction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Construction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstStep" eType="#//Component"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextStep" eType="#//Component"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cellar" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Basement" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="SaddleRoof" eSuperTypes="#//Component"/>
</ecore:EPackage>
