<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ProcessCodeAdapter" nsURI="platform:/resource/ProcessCodeAdapter/model/ProcessCodeAdapter.ecore"
    nsPrefix="ProcessCodeAdapter">
  <eClassifiers xsi:type="ecore:EClass" name="FileToTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/MocaTree/model/MocaTree.ecore#//File"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ProcessDefinition/model/ProcessDefinition.ecore#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FolderToSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/MocaTree/model/MocaTree.ecore#//Folder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ProcessDefinition/model/ProcessDefinition.ecore#//SystemModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToImport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ProcessDefinition/model/ProcessDefinition.ecore#//Import"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToInvocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ProcessDefinition/model/ProcessDefinition.ecore#//Invocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FolderToModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/MocaTree/model/MocaTree.ecore#//Folder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ProcessDefinition/model/ProcessDefinition.ecore#//Module"/>
  </eClassifiers>
</ecore:EPackage>
