<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simpleClassInheritance" nsURI="platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore"
    nsPrefix="simpleClassInheritance">
  <eClassifiers xsi:type="ecore:EClass" name="Clazz" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//Method" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClazz" eType="#//Clazz"
        eOpposite="#//Clazz/subClazzes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subClazzes" upperBound="-1"
        eType="#//Clazz" containment="true" eOpposite="#//Clazz/superClazz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClazzContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clazzes" upperBound="-1"
        eType="#//Clazz" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
