<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ProcessDefinition" nsURI="platform:/resource/ProcessDefinition/model/ProcessDefinition.ecore"
    nsPrefix="ProcessDefinition">
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importingTask" lowerBound="1"
        eType="#//Task" eOpposite="#//Task/imports"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module" eOpposite="#//Module/import"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1" eType="#//Task"
        eOpposite="#//Task/invocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokedTask" lowerBound="1"
        eType="#//Task" eOpposite="#//Task/invocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemModule" lowerBound="1"
        eType="#//SystemModule" eOpposite="#//SystemModule/allModules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="import" lowerBound="1"
        eType="#//Import" eOpposite="#//Import/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true" eOpposite="#//Task/module"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="helper" lowerBound="1"
        eType="#//facade/Helper" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allTasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/systemModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allModules" upperBound="-1"
        eType="#//Module" containment="true" eOpposite="#//Module/systemModule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemModule" lowerBound="1"
        eType="#//SystemModule" eOpposite="#//SystemModule/allTasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module" eOpposite="#//Module/tasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocation" upperBound="-1"
        eType="#//Invocation" eOpposite="#//Invocation/invokedTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocations" upperBound="-1"
        eType="#//Invocation" containment="true" eOpposite="#//Invocation/task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true" eOpposite="#//Import/importingTask"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="facade" nsURI="platform:/plugin/ProcessDefinition/model/ProcessDefinition.ecore#//facade"
      nsPrefix="facade">
    <eClassifiers xsi:type="ecore:EClass" name="Helper">
      <eOperations name="outputCycle">
        <eParameters name="currentTask" eType="#//Task"/>
      </eOperations>
      <eOperations name="print">
        <eParameters name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="coloredTask" upperBound="-1"
          eType="#//Task"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="visitedTasks" upperBound="-1"
          eType="#//Task"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
          eType="#//Task"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
