<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MocaTreeToProcess" nsURI="platform:/resource/MocaTreeToProcess/model/MocaTreeToProcess.ecore"
    nsPrefix="MocaTreeToProcess">
  <eClassifiers xsi:type="ecore:EClass" name="FolderToSystemModuleCorr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/MocaTree/model/MocaTree.ecore#//Folder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ProcessDefinition/model/ProcessDefinition.ecore#//SystemModule"/>
  </eClassifiers>
</ecore:EPackage>
