<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MetamodelInheritance3" nsURI="platform:/resource/MetamodelInheritance3/model/MetamodelInheritance3.ecore"
    nsPrefix="metamodel_inheritance3">
  <eClassifiers xsi:type="ecore:EClass" name="ChildC" eSuperTypes="../../MetamodelInheritance/model/MetamodelInheritance.ecore#//BaseContaineeC">
    <eStructuralFeatures xsi:type="ecore:EReference" name="d" upperBound="-1" eType="#//ChildD"
        eOpposite="#//ChildD/c"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildD" eSuperTypes="../../MetamodelInheritance2/model/MetamodelInheritance2.ecore#//ChildContaineeD">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c" upperBound="-1" eType="#//ChildC"
        eOpposite="#//ChildC/d"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" upperBound="-1" eType="ecore:EClass ../../MetamodelInheritance/model/MetamodelInheritance.ecore#//BaseContaineeA"/>
  </eClassifiers>
</ecore:EPackage>
