/**
 * generated by Xtext 2.37.0
 */
package org.emoflon.express.express.impl;

import org.eclipse.emf.ecore.EClass;

import org.emoflon.express.express.BooleanAttribute;
import org.emoflon.express.express.ExpressPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Boolean Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BooleanAttributeImpl extends AttributeImpl implements BooleanAttribute
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BooleanAttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressPackage.Literals.BOOLEAN_ATTRIBUTE;
  }

} //BooleanAttributeImpl
