/**
 * generated by Xtext 2.28.0
 */
package org.emoflon.express.express.impl;

import org.eclipse.emf.ecore.EClass;

import org.emoflon.express.express.ExpressPackage;
import org.emoflon.express.express.IntegerAttribute;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Integer Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IntegerAttributeImpl extends AttributeImpl implements IntegerAttribute
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntegerAttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressPackage.Literals.INTEGER_ATTRIBUTE;
  }

} //IntegerAttributeImpl
