/**
 * generated by Xtext 2.37.0
 */
package org.emoflon.express.express.impl;

import org.eclipse.emf.ecore.EClass;

import org.emoflon.express.express.ExpressPackage;
import org.emoflon.express.express.RealAttribute;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Real Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RealAttributeImpl extends AttributeImpl implements RealAttribute
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RealAttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressPackage.Literals.REAL_ATTRIBUTE;
  }

} //RealAttributeImpl
