/**
 * generated by Xtext 2.28.0
 */
package org.emoflon.express.express.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.emoflon.express.express.ExpressPackage;
import org.emoflon.express.express.Schema;
import org.emoflon.express.express.SchemaContainer;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Schema Container</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.express.express.impl.SchemaContainerImpl#getSchemas <em>Schemas</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SchemaContainerImpl extends MinimalEObjectImpl.Container implements SchemaContainer
{
  /**
   * The cached value of the '{@link #getSchemas() <em>Schemas</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSchemas()
   * @generated
   * @ordered
   */
  protected EList<Schema> schemas;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SchemaContainerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressPackage.Literals.SCHEMA_CONTAINER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Schema> getSchemas()
  {
    if (schemas == null)
    {
      schemas = new EObjectContainmentEList<Schema>(Schema.class, this, ExpressPackage.SCHEMA_CONTAINER__SCHEMAS);
    }
    return schemas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ExpressPackage.SCHEMA_CONTAINER__SCHEMAS:
        return ((InternalEList<?>)getSchemas()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ExpressPackage.SCHEMA_CONTAINER__SCHEMAS:
        return getSchemas();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ExpressPackage.SCHEMA_CONTAINER__SCHEMAS:
        getSchemas().clear();
        getSchemas().addAll((Collection<? extends Schema>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ExpressPackage.SCHEMA_CONTAINER__SCHEMAS:
        getSchemas().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ExpressPackage.SCHEMA_CONTAINER__SCHEMAS:
        return schemas != null && !schemas.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //SchemaContainerImpl
