/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.express.express.impl;

import org.eclipse.emf.ecore.EClass;

import org.emoflon.express.express.ExpressPackage;
import org.emoflon.express.express.StringAttribute;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>String Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StringAttributeImpl extends AttributeImpl implements StringAttribute
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StringAttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressPackage.Literals.STRING_ATTRIBUTE;
  }

} //StringAttributeImpl
