/*
 * generated by Xtext 2.22.0
 */
package org.emoflon.express.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ExpressUiModule extends AbstractExpressUiModule {

	public ExpressUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
