/*
 * generated by Xtext 2.22.0
 */
package org.emoflon.express;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpressRuntimeModule extends AbstractExpressRuntimeModule {
}
