/*
 * generated by Xtext 2.22.0
 */
package org.emoflon.express;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ExpressStandaloneSetup extends ExpressStandaloneSetupGenerated {

	public static void doSetup() {
		new ExpressStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
