<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="URIFragmentEMF" nsURI="platform:/resource/URIFragment/model/URIFragmentEMF.ecore"
    nsPrefix="URIFragmentEMF">
  <eClassifiers xsi:type="ecore:EClass" name="Tree" eSuperTypes="#//NamedNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" upperBound="-1"
        eType="#//Branch" containment="true" eOpposite="#//Branch/tree"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch" eSuperTypes="#//NamedNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tree" eType="#//Tree" eOpposite="#//Tree/branches"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leaves" upperBound="-1"
        eType="#//Leaf" containment="true" eOpposite="#//Leaf/branch"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subBranches" upperBound="-1"
        eType="#//Branch" containment="true" eOpposite="#//Branch/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Branch"
        eOpposite="#//Branch/subBranches"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="apples" upperBound="-1"
        eType="#//Apple" containment="true" eOpposite="#//Apple/branch"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leaf" eSuperTypes="#//NamedNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Green"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branch" eType="#//Branch"
        eOpposite="#//Branch/leaves"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Apple" eSuperTypes="#//NamedNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appleID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branch" eType="#//Branch"
        eOpposite="#//Branch/apples"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedNode" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
