<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Adele2Aadl" nsURI="platform:/resource/Adele2Aadl/model/Adele2Aadl.ecore"
    nsPrefix="Adele2Aadl">
  <eClassifiers xsi:type="ecore:EClass" name="CorrAxiomAP">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Adele2Aadl/metamodels/src/ADELE_Components.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/Adele2Aadl/metamodels/trg/aadl2.ecore#//AadlPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorrAxiomAPOne">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Adele2Aadl/metamodels/src/ADELE_Components.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/Adele2Aadl/metamodels/trg/aadl2.ecore#//PublicPackageSection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="rulePackage2AadlPackage__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__adelePackage"
        lowerBound="1" eType="ecore:EClass platform:/resource/Adele2Aadl/metamodels/src/ADELE_Components.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__aadlPackage"
        lowerBound="1" eType="ecore:EClass platform:/resource/Adele2Aadl/metamodels/trg/aadl2.ecore#//AadlPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__aadlPublicPackageSection"
        lowerBound="1" eType="ecore:EClass platform:/resource/Adele2Aadl/metamodels/trg/aadl2.ecore#//PublicPackageSection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__corrAxiom"
        lowerBound="1" eType="ecore:EClass platform:/resource/Adele2Aadl/model/Adele2Aadl.ecore#//CorrAxiomAP"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__corrAxiomOne"
        lowerBound="1" eType="ecore:EClass platform:/resource/Adele2Aadl/model/Adele2Aadl.ecore#//CorrAxiomAPOne"/>
  </eClassifiers>
</ecore:EPackage>
