<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="VHDLTGGCodeAdapter" nsURI="platform:/resource/VHDLTGGCodeAdapter/model/VHDLTGGCodeAdapter.ecore"
    nsPrefix="VHDLTGGCodeAdapter">
  <eClassifiers xsi:type="ecore:EClass" name="NodeToInputPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass ../../MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ../../VHDLModel/model/VHDLModel.ecore#//InputPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass ../../MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ../../VHDLModel/model/VHDLModel.ecore#//Block"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToCompositeBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass ../../MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ../../VHDLModel/model/VHDLModel.ecore#//CompositeBlock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileToVHDLSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass ../../MocaTree/model/MocaTree.ecore#//File"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ../../VHDLModel/model/VHDLModel.ecore#//VHDLSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToOutputPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass ../../MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ../../VHDLModel/model/VHDLModel.ecore#//OutputPort"/>
  </eClassifiers>
</ecore:EPackage>
