<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AdvancedTrain" nsURI="platform:/resource/AdvancedTrain/model/AdvancedTrain.ecore"
    nsPrefix="AdvancedTrain">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TODO: Add documentation for AdvancedTrain. Hint: You may copy this element in the Ecore editor to add documentation to EClasses, EOperations, ..."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Train">
    <eStructuralFeatures xsi:type="ecore:EReference" name="locomotive" lowerBound="1"
        eType="#//Locomotive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wagons" upperBound="-1"
        eType="#//Wagon" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Locomotive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" lowerBound="1"
        eType="#//LocomotiveDriver" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstWagon" eType="#//Wagon"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wagon">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextWagon" eType="#//Wagon"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="benchSeats" upperBound="-1"
        eType="#//BenchSeat" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocomotiveDriver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenchSeat"/>
</ecore:EPackage>
