/*
 * generated by Xtext 2.28.0
 */
package org.emoflon.express.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.emoflon.express.parser.antlr.internal.InternalExpressParser;
import org.emoflon.express.services.ExpressGrammarAccess;

public class ExpressParser extends AbstractAntlrParser {

	@Inject
	private ExpressGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalExpressParser createParser(XtextTokenStream stream) {
		return new InternalExpressParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SchemaContainer";
	}

	public ExpressGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ExpressGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
