package org.emoflon.ibex.tgg.run.adele2aadl;

import java.io.IOException;

import org.emoflon.ibex.tgg.operational.strategies.OperationalStrategy;

/**
 * Generated by eMoflon::IBeX.
 * 
 * Do not edit this class. It is automatically generated and is kept in sync
 * with the imports in your Schema.tgg file.
 */
public class _SchemaBasedAutoRegistration {
	
	public static void register(OperationalStrategy strategy) throws IOException {
		strategy.loadAndRegisterMetamodel("platform:/resource/Adele2Aadl/metamodels/trg/aadl2.ecore");
		strategy.loadAndRegisterMetamodel("platform:/resource/Adele2Aadl/metamodels/trg/instance.ecore");
		strategy.loadAndRegisterMetamodel("platform:/resource/Adele2Aadl/metamodels/src/ADELE_Components.ecore");
		strategy.loadAndRegisterMetamodel("platform:/resource/Adele2Aadl/metamodels/src/ADELE_Features.ecore");
		strategy.loadAndRegisterMetamodel("platform:/resource/Adele2Aadl/metamodels/src/ADELE_Relations.ecore");
		strategy.loadAndRegisterMetamodel("platform:/resource/Adele2Aadl/metamodels/src/BA_components.ecore");
		strategy.loadAndRegisterMetamodel("platform:/resource/Adele2Aadl/metamodels/src/BA_features.ecore");
		strategy.loadAndRegisterMetamodel("platform:/resource/Adele2Aadl/metamodels/src/BA_relations.ecore");
		strategy.loadAndRegisterMetamodel("platform:/resource/Adele2Aadl/metamodels/src/KernelSpices.ecore");
		strategy.loadAndRegisterMetamodel("platform:/resource/Adele2Aadl/metamodels/src/ObjectDescriptionModel.ecore");
	}
	
}
