/**
 * generated by Xtext 2.28.0
 */
package org.emoflon.express.express;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alias Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.express.express.AliasType#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see org.emoflon.express.express.ExpressPackage#getAliasType()
 * @model
 * @generated
 */
public interface AliasType extends UserDefinedType
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' reference.
   * @see #setElement(UserDefinedType)
   * @see org.emoflon.express.express.ExpressPackage#getAliasType_Element()
   * @model
   * @generated
   */
  UserDefinedType getElement();

  /**
   * Sets the value of the '{@link org.emoflon.express.express.AliasType#getElement <em>Element</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' reference.
   * @see #getElement()
   * @generated
   */
  void setElement(UserDefinedType value);

} // AliasType
