/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.express.express;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.emoflon.express.express.ExpressPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends EObject
{
} // Declaration
