/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.express.express;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enumeration Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.express.express.EnumerationType#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see org.emoflon.express.express.ExpressPackage#getEnumerationType()
 * @model
 * @generated
 */
public interface EnumerationType extends UserDefinedType
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' containment reference list.
   * The list contents are of type {@link org.emoflon.express.express.EnumerationValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' containment reference list.
   * @see org.emoflon.express.express.ExpressPackage#getEnumerationType_Values()
   * @model containment="true"
   * @generated
   */
  EList<EnumerationValue> getValues();

} // EnumerationType
