/**
 * generated by Xtext 2.28.0
 */
package org.emoflon.express.express;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.emoflon.express.express.ExpressFactory
 * @model kind="package"
 * @generated
 */
public interface ExpressPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "express";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "platform:/org.emoflon.express/model/generated/Express.ecore";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "express";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ExpressPackage eINSTANCE = org.emoflon.express.express.impl.ExpressPackageImpl.init();

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.SchemaContainerImpl <em>Schema Container</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.SchemaContainerImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getSchemaContainer()
   * @generated
   */
  int SCHEMA_CONTAINER = 0;

  /**
   * The feature id for the '<em><b>Schemas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_CONTAINER__SCHEMAS = 0;

  /**
   * The number of structural features of the '<em>Schema Container</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_CONTAINER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.SchemaImpl <em>Schema</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.SchemaImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getSchema()
   * @generated
   */
  int SCHEMA = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA__NAME = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA__DECLARATIONS = 1;

  /**
   * The number of structural features of the '<em>Schema</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.DeclarationImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 2;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.ReferenceOrValueImpl <em>Reference Or Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.ReferenceOrValueImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getReferenceOrValue()
   * @generated
   */
  int REFERENCE_OR_VALUE = 3;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_OR_VALUE__REFERENCE = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_OR_VALUE__VALUE = 1;

  /**
   * The number of structural features of the '<em>Reference Or Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_OR_VALUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.UserDefinedTypeImpl <em>User Defined Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.UserDefinedTypeImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getUserDefinedType()
   * @generated
   */
  int USER_DEFINED_TYPE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_DEFINED_TYPE__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>User Defined Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_DEFINED_TYPE_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.UseFromImpl <em>Use From</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.UseFromImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getUseFrom()
   * @generated
   */
  int USE_FROM = 5;

  /**
   * The feature id for the '<em><b>Schema</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_FROM__SCHEMA = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Imported Entities</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_FROM__IMPORTED_ENTITIES = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Use From</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_FROM_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.ImportedEntityListImpl <em>Imported Entity List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.ImportedEntityListImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getImportedEntityList()
   * @generated
   */
  int IMPORTED_ENTITY_LIST = 6;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORTED_ENTITY_LIST__ENTITIES = 0;

  /**
   * The number of structural features of the '<em>Imported Entity List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORTED_ENTITY_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.ImportedEntityImpl <em>Imported Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.ImportedEntityImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getImportedEntity()
   * @generated
   */
  int IMPORTED_ENTITY = 7;

  /**
   * The feature id for the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORTED_ENTITY__ENTITY = 0;

  /**
   * The feature id for the '<em><b>Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORTED_ENTITY__ALIAS = 1;

  /**
   * The number of structural features of the '<em>Imported Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORTED_ENTITY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.SelectTypeImpl <em>Select Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.SelectTypeImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getSelectType()
   * @generated
   */
  int SELECT_TYPE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_TYPE__NAME = USER_DEFINED_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_TYPE__TYPES = USER_DEFINED_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Select Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_TYPE_FEATURE_COUNT = USER_DEFINED_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.EnumerationTypeImpl <em>Enumeration Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.EnumerationTypeImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getEnumerationType()
   * @generated
   */
  int ENUMERATION_TYPE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATION_TYPE__NAME = USER_DEFINED_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATION_TYPE__VALUES = USER_DEFINED_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Enumeration Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATION_TYPE_FEATURE_COUNT = USER_DEFINED_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.EnumerationValueImpl <em>Enumeration Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.EnumerationValueImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getEnumerationValue()
   * @generated
   */
  int ENUMERATION_VALUE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATION_VALUE__NAME = 0;

  /**
   * The number of structural features of the '<em>Enumeration Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATION_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.AliasTypeImpl <em>Alias Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.AliasTypeImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getAliasType()
   * @generated
   */
  int ALIAS_TYPE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS_TYPE__NAME = USER_DEFINED_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS_TYPE__ELEMENT = USER_DEFINED_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Alias Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS_TYPE_FEATURE_COUNT = USER_DEFINED_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.EntityImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = USER_DEFINED_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Sub Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__SUB_TYPE = USER_DEFINED_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__SUPER_TYPE = USER_DEFINED_TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__ATTRIBUTES = USER_DEFINED_TYPE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = USER_DEFINED_TYPE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.FunctionImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__PARAMETERS = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__RETURN_TYPE = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.ParameterListImpl <em>Parameter List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.ParameterListImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getParameterList()
   * @generated
   */
  int PARAMETER_LIST = 14;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_LIST__PARAMETERS = 0;

  /**
   * The number of structural features of the '<em>Parameter List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.ParameterImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__TYPE = 1;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.UserDefinedTypeListImpl <em>User Defined Type List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.UserDefinedTypeListImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getUserDefinedTypeList()
   * @generated
   */
  int USER_DEFINED_TYPE_LIST = 16;

  /**
   * The feature id for the '<em><b>Elements</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_DEFINED_TYPE_LIST__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>User Defined Type List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_DEFINED_TYPE_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.AttributeImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__OPTIONAL = 1;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.IntegerAttributeImpl <em>Integer Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.IntegerAttributeImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getIntegerAttribute()
   * @generated
   */
  int INTEGER_ATTRIBUTE = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_ATTRIBUTE__NAME = ATTRIBUTE__NAME;

  /**
   * The feature id for the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_ATTRIBUTE__OPTIONAL = ATTRIBUTE__OPTIONAL;

  /**
   * The number of structural features of the '<em>Integer Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_ATTRIBUTE_FEATURE_COUNT = ATTRIBUTE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.StringAttributeImpl <em>String Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.StringAttributeImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getStringAttribute()
   * @generated
   */
  int STRING_ATTRIBUTE = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_ATTRIBUTE__NAME = ATTRIBUTE__NAME;

  /**
   * The feature id for the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_ATTRIBUTE__OPTIONAL = ATTRIBUTE__OPTIONAL;

  /**
   * The number of structural features of the '<em>String Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_ATTRIBUTE_FEATURE_COUNT = ATTRIBUTE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.RealAttributeImpl <em>Real Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.RealAttributeImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getRealAttribute()
   * @generated
   */
  int REAL_ATTRIBUTE = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_ATTRIBUTE__NAME = ATTRIBUTE__NAME;

  /**
   * The feature id for the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_ATTRIBUTE__OPTIONAL = ATTRIBUTE__OPTIONAL;

  /**
   * The number of structural features of the '<em>Real Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_ATTRIBUTE_FEATURE_COUNT = ATTRIBUTE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.BooleanAttributeImpl <em>Boolean Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.BooleanAttributeImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getBooleanAttribute()
   * @generated
   */
  int BOOLEAN_ATTRIBUTE = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_ATTRIBUTE__NAME = ATTRIBUTE__NAME;

  /**
   * The feature id for the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_ATTRIBUTE__OPTIONAL = ATTRIBUTE__OPTIONAL;

  /**
   * The number of structural features of the '<em>Boolean Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_ATTRIBUTE_FEATURE_COUNT = ATTRIBUTE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.emoflon.express.express.impl.ReferenceAttributeImpl <em>Reference Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emoflon.express.express.impl.ReferenceAttributeImpl
   * @see org.emoflon.express.express.impl.ExpressPackageImpl#getReferenceAttribute()
   * @generated
   */
  int REFERENCE_ATTRIBUTE = 22;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_ATTRIBUTE__NAME = ATTRIBUTE__NAME;

  /**
   * The feature id for the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_ATTRIBUTE__OPTIONAL = ATTRIBUTE__OPTIONAL;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_ATTRIBUTE__REFERENCE = ATTRIBUTE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Reference Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_ATTRIBUTE_FEATURE_COUNT = ATTRIBUTE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.SchemaContainer <em>Schema Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schema Container</em>'.
   * @see org.emoflon.express.express.SchemaContainer
   * @generated
   */
  EClass getSchemaContainer();

  /**
   * Returns the meta object for the containment reference list '{@link org.emoflon.express.express.SchemaContainer#getSchemas <em>Schemas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Schemas</em>'.
   * @see org.emoflon.express.express.SchemaContainer#getSchemas()
   * @see #getSchemaContainer()
   * @generated
   */
  EReference getSchemaContainer_Schemas();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.Schema <em>Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schema</em>'.
   * @see org.emoflon.express.express.Schema
   * @generated
   */
  EClass getSchema();

  /**
   * Returns the meta object for the attribute '{@link org.emoflon.express.express.Schema#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.emoflon.express.express.Schema#getName()
   * @see #getSchema()
   * @generated
   */
  EAttribute getSchema_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.emoflon.express.express.Schema#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see org.emoflon.express.express.Schema#getDeclarations()
   * @see #getSchema()
   * @generated
   */
  EReference getSchema_Declarations();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see org.emoflon.express.express.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.ReferenceOrValue <em>Reference Or Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference Or Value</em>'.
   * @see org.emoflon.express.express.ReferenceOrValue
   * @generated
   */
  EClass getReferenceOrValue();

  /**
   * Returns the meta object for the reference '{@link org.emoflon.express.express.ReferenceOrValue#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Reference</em>'.
   * @see org.emoflon.express.express.ReferenceOrValue#getReference()
   * @see #getReferenceOrValue()
   * @generated
   */
  EReference getReferenceOrValue_Reference();

  /**
   * Returns the meta object for the attribute '{@link org.emoflon.express.express.ReferenceOrValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.emoflon.express.express.ReferenceOrValue#getValue()
   * @see #getReferenceOrValue()
   * @generated
   */
  EAttribute getReferenceOrValue_Value();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.UserDefinedType <em>User Defined Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Defined Type</em>'.
   * @see org.emoflon.express.express.UserDefinedType
   * @generated
   */
  EClass getUserDefinedType();

  /**
   * Returns the meta object for the attribute '{@link org.emoflon.express.express.UserDefinedType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.emoflon.express.express.UserDefinedType#getName()
   * @see #getUserDefinedType()
   * @generated
   */
  EAttribute getUserDefinedType_Name();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.UseFrom <em>Use From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use From</em>'.
   * @see org.emoflon.express.express.UseFrom
   * @generated
   */
  EClass getUseFrom();

  /**
   * Returns the meta object for the reference '{@link org.emoflon.express.express.UseFrom#getSchema <em>Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Schema</em>'.
   * @see org.emoflon.express.express.UseFrom#getSchema()
   * @see #getUseFrom()
   * @generated
   */
  EReference getUseFrom_Schema();

  /**
   * Returns the meta object for the containment reference '{@link org.emoflon.express.express.UseFrom#getImportedEntities <em>Imported Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Imported Entities</em>'.
   * @see org.emoflon.express.express.UseFrom#getImportedEntities()
   * @see #getUseFrom()
   * @generated
   */
  EReference getUseFrom_ImportedEntities();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.ImportedEntityList <em>Imported Entity List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Imported Entity List</em>'.
   * @see org.emoflon.express.express.ImportedEntityList
   * @generated
   */
  EClass getImportedEntityList();

  /**
   * Returns the meta object for the containment reference list '{@link org.emoflon.express.express.ImportedEntityList#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see org.emoflon.express.express.ImportedEntityList#getEntities()
   * @see #getImportedEntityList()
   * @generated
   */
  EReference getImportedEntityList_Entities();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.ImportedEntity <em>Imported Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Imported Entity</em>'.
   * @see org.emoflon.express.express.ImportedEntity
   * @generated
   */
  EClass getImportedEntity();

  /**
   * Returns the meta object for the reference '{@link org.emoflon.express.express.ImportedEntity#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entity</em>'.
   * @see org.emoflon.express.express.ImportedEntity#getEntity()
   * @see #getImportedEntity()
   * @generated
   */
  EReference getImportedEntity_Entity();

  /**
   * Returns the meta object for the attribute '{@link org.emoflon.express.express.ImportedEntity#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alias</em>'.
   * @see org.emoflon.express.express.ImportedEntity#getAlias()
   * @see #getImportedEntity()
   * @generated
   */
  EAttribute getImportedEntity_Alias();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.SelectType <em>Select Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Type</em>'.
   * @see org.emoflon.express.express.SelectType
   * @generated
   */
  EClass getSelectType();

  /**
   * Returns the meta object for the containment reference '{@link org.emoflon.express.express.SelectType#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Types</em>'.
   * @see org.emoflon.express.express.SelectType#getTypes()
   * @see #getSelectType()
   * @generated
   */
  EReference getSelectType_Types();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.EnumerationType <em>Enumeration Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enumeration Type</em>'.
   * @see org.emoflon.express.express.EnumerationType
   * @generated
   */
  EClass getEnumerationType();

  /**
   * Returns the meta object for the containment reference list '{@link org.emoflon.express.express.EnumerationType#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see org.emoflon.express.express.EnumerationType#getValues()
   * @see #getEnumerationType()
   * @generated
   */
  EReference getEnumerationType_Values();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.EnumerationValue <em>Enumeration Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enumeration Value</em>'.
   * @see org.emoflon.express.express.EnumerationValue
   * @generated
   */
  EClass getEnumerationValue();

  /**
   * Returns the meta object for the attribute '{@link org.emoflon.express.express.EnumerationValue#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.emoflon.express.express.EnumerationValue#getName()
   * @see #getEnumerationValue()
   * @generated
   */
  EAttribute getEnumerationValue_Name();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.AliasType <em>Alias Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alias Type</em>'.
   * @see org.emoflon.express.express.AliasType
   * @generated
   */
  EClass getAliasType();

  /**
   * Returns the meta object for the reference '{@link org.emoflon.express.express.AliasType#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Element</em>'.
   * @see org.emoflon.express.express.AliasType#getElement()
   * @see #getAliasType()
   * @generated
   */
  EReference getAliasType_Element();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.emoflon.express.express.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the reference '{@link org.emoflon.express.express.Entity#getSubType <em>Sub Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sub Type</em>'.
   * @see org.emoflon.express.express.Entity#getSubType()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_SubType();

  /**
   * Returns the meta object for the reference '{@link org.emoflon.express.express.Entity#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.emoflon.express.express.Entity#getSuperType()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link org.emoflon.express.express.Entity#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.emoflon.express.express.Entity#getAttributes()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Attributes();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see org.emoflon.express.express.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link org.emoflon.express.express.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.emoflon.express.express.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.emoflon.express.express.Function#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameters</em>'.
   * @see org.emoflon.express.express.Function#getParameters()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Parameters();

  /**
   * Returns the meta object for the containment reference '{@link org.emoflon.express.express.Function#getReturnType <em>Return Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return Type</em>'.
   * @see org.emoflon.express.express.Function#getReturnType()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_ReturnType();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.ParameterList <em>Parameter List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter List</em>'.
   * @see org.emoflon.express.express.ParameterList
   * @generated
   */
  EClass getParameterList();

  /**
   * Returns the meta object for the containment reference list '{@link org.emoflon.express.express.ParameterList#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see org.emoflon.express.express.ParameterList#getParameters()
   * @see #getParameterList()
   * @generated
   */
  EReference getParameterList_Parameters();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.emoflon.express.express.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link org.emoflon.express.express.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.emoflon.express.express.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.emoflon.express.express.Parameter#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.emoflon.express.express.Parameter#getType()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Type();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.UserDefinedTypeList <em>User Defined Type List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Defined Type List</em>'.
   * @see org.emoflon.express.express.UserDefinedTypeList
   * @generated
   */
  EClass getUserDefinedTypeList();

  /**
   * Returns the meta object for the reference list '{@link org.emoflon.express.express.UserDefinedTypeList#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Elements</em>'.
   * @see org.emoflon.express.express.UserDefinedTypeList#getElements()
   * @see #getUserDefinedTypeList()
   * @generated
   */
  EReference getUserDefinedTypeList_Elements();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see org.emoflon.express.express.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.emoflon.express.express.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.emoflon.express.express.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the attribute '{@link org.emoflon.express.express.Attribute#isOptional <em>Optional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Optional</em>'.
   * @see org.emoflon.express.express.Attribute#isOptional()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Optional();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.IntegerAttribute <em>Integer Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer Attribute</em>'.
   * @see org.emoflon.express.express.IntegerAttribute
   * @generated
   */
  EClass getIntegerAttribute();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.StringAttribute <em>String Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Attribute</em>'.
   * @see org.emoflon.express.express.StringAttribute
   * @generated
   */
  EClass getStringAttribute();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.RealAttribute <em>Real Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Real Attribute</em>'.
   * @see org.emoflon.express.express.RealAttribute
   * @generated
   */
  EClass getRealAttribute();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.BooleanAttribute <em>Boolean Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Attribute</em>'.
   * @see org.emoflon.express.express.BooleanAttribute
   * @generated
   */
  EClass getBooleanAttribute();

  /**
   * Returns the meta object for class '{@link org.emoflon.express.express.ReferenceAttribute <em>Reference Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference Attribute</em>'.
   * @see org.emoflon.express.express.ReferenceAttribute
   * @generated
   */
  EClass getReferenceAttribute();

  /**
   * Returns the meta object for the reference '{@link org.emoflon.express.express.ReferenceAttribute#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Reference</em>'.
   * @see org.emoflon.express.express.ReferenceAttribute#getReference()
   * @see #getReferenceAttribute()
   * @generated
   */
  EReference getReferenceAttribute_Reference();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ExpressFactory getExpressFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.SchemaContainerImpl <em>Schema Container</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.SchemaContainerImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getSchemaContainer()
     * @generated
     */
    EClass SCHEMA_CONTAINER = eINSTANCE.getSchemaContainer();

    /**
     * The meta object literal for the '<em><b>Schemas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEMA_CONTAINER__SCHEMAS = eINSTANCE.getSchemaContainer_Schemas();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.SchemaImpl <em>Schema</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.SchemaImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getSchema()
     * @generated
     */
    EClass SCHEMA = eINSTANCE.getSchema();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHEMA__NAME = eINSTANCE.getSchema_Name();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEMA__DECLARATIONS = eINSTANCE.getSchema_Declarations();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.DeclarationImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.ReferenceOrValueImpl <em>Reference Or Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.ReferenceOrValueImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getReferenceOrValue()
     * @generated
     */
    EClass REFERENCE_OR_VALUE = eINSTANCE.getReferenceOrValue();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE_OR_VALUE__REFERENCE = eINSTANCE.getReferenceOrValue_Reference();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REFERENCE_OR_VALUE__VALUE = eINSTANCE.getReferenceOrValue_Value();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.UserDefinedTypeImpl <em>User Defined Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.UserDefinedTypeImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getUserDefinedType()
     * @generated
     */
    EClass USER_DEFINED_TYPE = eINSTANCE.getUserDefinedType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_DEFINED_TYPE__NAME = eINSTANCE.getUserDefinedType_Name();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.UseFromImpl <em>Use From</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.UseFromImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getUseFrom()
     * @generated
     */
    EClass USE_FROM = eINSTANCE.getUseFrom();

    /**
     * The meta object literal for the '<em><b>Schema</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_FROM__SCHEMA = eINSTANCE.getUseFrom_Schema();

    /**
     * The meta object literal for the '<em><b>Imported Entities</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_FROM__IMPORTED_ENTITIES = eINSTANCE.getUseFrom_ImportedEntities();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.ImportedEntityListImpl <em>Imported Entity List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.ImportedEntityListImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getImportedEntityList()
     * @generated
     */
    EClass IMPORTED_ENTITY_LIST = eINSTANCE.getImportedEntityList();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORTED_ENTITY_LIST__ENTITIES = eINSTANCE.getImportedEntityList_Entities();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.ImportedEntityImpl <em>Imported Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.ImportedEntityImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getImportedEntity()
     * @generated
     */
    EClass IMPORTED_ENTITY = eINSTANCE.getImportedEntity();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORTED_ENTITY__ENTITY = eINSTANCE.getImportedEntity_Entity();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORTED_ENTITY__ALIAS = eINSTANCE.getImportedEntity_Alias();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.SelectTypeImpl <em>Select Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.SelectTypeImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getSelectType()
     * @generated
     */
    EClass SELECT_TYPE = eINSTANCE.getSelectType();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_TYPE__TYPES = eINSTANCE.getSelectType_Types();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.EnumerationTypeImpl <em>Enumeration Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.EnumerationTypeImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getEnumerationType()
     * @generated
     */
    EClass ENUMERATION_TYPE = eINSTANCE.getEnumerationType();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUMERATION_TYPE__VALUES = eINSTANCE.getEnumerationType_Values();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.EnumerationValueImpl <em>Enumeration Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.EnumerationValueImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getEnumerationValue()
     * @generated
     */
    EClass ENUMERATION_VALUE = eINSTANCE.getEnumerationValue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUMERATION_VALUE__NAME = eINSTANCE.getEnumerationValue_Name();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.AliasTypeImpl <em>Alias Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.AliasTypeImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getAliasType()
     * @generated
     */
    EClass ALIAS_TYPE = eINSTANCE.getAliasType();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALIAS_TYPE__ELEMENT = eINSTANCE.getAliasType_Element();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.EntityImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Sub Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__SUB_TYPE = eINSTANCE.getEntity_SubType();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__SUPER_TYPE = eINSTANCE.getEntity_SuperType();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__ATTRIBUTES = eINSTANCE.getEntity_Attributes();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.FunctionImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__PARAMETERS = eINSTANCE.getFunction_Parameters();

    /**
     * The meta object literal for the '<em><b>Return Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__RETURN_TYPE = eINSTANCE.getFunction_ReturnType();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.ParameterListImpl <em>Parameter List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.ParameterListImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getParameterList()
     * @generated
     */
    EClass PARAMETER_LIST = eINSTANCE.getParameterList();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER_LIST__PARAMETERS = eINSTANCE.getParameterList_Parameters();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.ParameterImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__TYPE = eINSTANCE.getParameter_Type();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.UserDefinedTypeListImpl <em>User Defined Type List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.UserDefinedTypeListImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getUserDefinedTypeList()
     * @generated
     */
    EClass USER_DEFINED_TYPE_LIST = eINSTANCE.getUserDefinedTypeList();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_DEFINED_TYPE_LIST__ELEMENTS = eINSTANCE.getUserDefinedTypeList_Elements();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.AttributeImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Optional</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__OPTIONAL = eINSTANCE.getAttribute_Optional();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.IntegerAttributeImpl <em>Integer Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.IntegerAttributeImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getIntegerAttribute()
     * @generated
     */
    EClass INTEGER_ATTRIBUTE = eINSTANCE.getIntegerAttribute();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.StringAttributeImpl <em>String Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.StringAttributeImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getStringAttribute()
     * @generated
     */
    EClass STRING_ATTRIBUTE = eINSTANCE.getStringAttribute();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.RealAttributeImpl <em>Real Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.RealAttributeImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getRealAttribute()
     * @generated
     */
    EClass REAL_ATTRIBUTE = eINSTANCE.getRealAttribute();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.BooleanAttributeImpl <em>Boolean Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.BooleanAttributeImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getBooleanAttribute()
     * @generated
     */
    EClass BOOLEAN_ATTRIBUTE = eINSTANCE.getBooleanAttribute();

    /**
     * The meta object literal for the '{@link org.emoflon.express.express.impl.ReferenceAttributeImpl <em>Reference Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emoflon.express.express.impl.ReferenceAttributeImpl
     * @see org.emoflon.express.express.impl.ExpressPackageImpl#getReferenceAttribute()
     * @generated
     */
    EClass REFERENCE_ATTRIBUTE = eINSTANCE.getReferenceAttribute();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE_ATTRIBUTE__REFERENCE = eINSTANCE.getReferenceAttribute_Reference();

  }

} //ExpressPackage
