/**
 * generated by Xtext 2.28.0
 */
package org.emoflon.express.express;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.emoflon.express.express.ExpressPackage
 * @generated
 */
public interface ExpressFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ExpressFactory eINSTANCE = org.emoflon.express.express.impl.ExpressFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Schema Container</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Schema Container</em>'.
   * @generated
   */
  SchemaContainer createSchemaContainer();

  /**
   * Returns a new object of class '<em>Schema</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Schema</em>'.
   * @generated
   */
  Schema createSchema();

  /**
   * Returns a new object of class '<em>Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declaration</em>'.
   * @generated
   */
  Declaration createDeclaration();

  /**
   * Returns a new object of class '<em>Reference Or Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reference Or Value</em>'.
   * @generated
   */
  ReferenceOrValue createReferenceOrValue();

  /**
   * Returns a new object of class '<em>User Defined Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>User Defined Type</em>'.
   * @generated
   */
  UserDefinedType createUserDefinedType();

  /**
   * Returns a new object of class '<em>Use From</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Use From</em>'.
   * @generated
   */
  UseFrom createUseFrom();

  /**
   * Returns a new object of class '<em>Imported Entity List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imported Entity List</em>'.
   * @generated
   */
  ImportedEntityList createImportedEntityList();

  /**
   * Returns a new object of class '<em>Imported Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imported Entity</em>'.
   * @generated
   */
  ImportedEntity createImportedEntity();

  /**
   * Returns a new object of class '<em>Select Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Select Type</em>'.
   * @generated
   */
  SelectType createSelectType();

  /**
   * Returns a new object of class '<em>Enumeration Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enumeration Type</em>'.
   * @generated
   */
  EnumerationType createEnumerationType();

  /**
   * Returns a new object of class '<em>Enumeration Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enumeration Value</em>'.
   * @generated
   */
  EnumerationValue createEnumerationValue();

  /**
   * Returns a new object of class '<em>Alias Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alias Type</em>'.
   * @generated
   */
  AliasType createAliasType();

  /**
   * Returns a new object of class '<em>Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity</em>'.
   * @generated
   */
  Entity createEntity();

  /**
   * Returns a new object of class '<em>Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function</em>'.
   * @generated
   */
  Function createFunction();

  /**
   * Returns a new object of class '<em>Parameter List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter List</em>'.
   * @generated
   */
  ParameterList createParameterList();

  /**
   * Returns a new object of class '<em>Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter</em>'.
   * @generated
   */
  Parameter createParameter();

  /**
   * Returns a new object of class '<em>User Defined Type List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>User Defined Type List</em>'.
   * @generated
   */
  UserDefinedTypeList createUserDefinedTypeList();

  /**
   * Returns a new object of class '<em>Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute</em>'.
   * @generated
   */
  Attribute createAttribute();

  /**
   * Returns a new object of class '<em>Integer Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integer Attribute</em>'.
   * @generated
   */
  IntegerAttribute createIntegerAttribute();

  /**
   * Returns a new object of class '<em>String Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Attribute</em>'.
   * @generated
   */
  StringAttribute createStringAttribute();

  /**
   * Returns a new object of class '<em>Real Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Real Attribute</em>'.
   * @generated
   */
  RealAttribute createRealAttribute();

  /**
   * Returns a new object of class '<em>Boolean Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boolean Attribute</em>'.
   * @generated
   */
  BooleanAttribute createBooleanAttribute();

  /**
   * Returns a new object of class '<em>Reference Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reference Attribute</em>'.
   * @generated
   */
  ReferenceAttribute createReferenceAttribute();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ExpressPackage getExpressPackage();

} //ExpressFactory
