/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.express.express;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Imported Entity List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.express.express.ImportedEntityList#getEntities <em>Entities</em>}</li>
 * </ul>
 *
 * @see org.emoflon.express.express.ExpressPackage#getImportedEntityList()
 * @model
 * @generated
 */
public interface ImportedEntityList extends EObject
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link org.emoflon.express.express.ImportedEntity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see org.emoflon.express.express.ExpressPackage#getImportedEntityList_Entities()
   * @model containment="true"
   * @generated
   */
  EList<ImportedEntity> getEntities();

} // ImportedEntityList
