/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.express.express;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.emoflon.express.express.ExpressPackage#getIntegerAttribute()
 * @model
 * @generated
 */
public interface IntegerAttribute extends Attribute
{
} // IntegerAttribute
