/**
 * generated by Xtext 2.28.0
 */
package org.emoflon.express.express;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.emoflon.express.express.ExpressPackage#getRealAttribute()
 * @model
 * @generated
 */
public interface RealAttribute extends Attribute
{
} // RealAttribute
