/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.express.express;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Or Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.express.express.ReferenceOrValue#getReference <em>Reference</em>}</li>
 *   <li>{@link org.emoflon.express.express.ReferenceOrValue#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.emoflon.express.express.ExpressPackage#getReferenceOrValue()
 * @model
 * @generated
 */
public interface ReferenceOrValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' reference.
   * @see #setReference(UserDefinedType)
   * @see org.emoflon.express.express.ExpressPackage#getReferenceOrValue_Reference()
   * @model
   * @generated
   */
  UserDefinedType getReference();

  /**
   * Sets the value of the '{@link org.emoflon.express.express.ReferenceOrValue#getReference <em>Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' reference.
   * @see #getReference()
   * @generated
   */
  void setReference(UserDefinedType value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.emoflon.express.express.ExpressPackage#getReferenceOrValue_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.emoflon.express.express.ReferenceOrValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // ReferenceOrValue
