/**
 * generated by Xtext 2.28.0
 */
package org.emoflon.express.express;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.express.express.ReferenceAttribute#getReference <em>Reference</em>}</li>
 * </ul>
 *
 * @see org.emoflon.express.express.ExpressPackage#getReferenceAttribute()
 * @model
 * @generated
 */
public interface ReferenceAttribute extends Attribute
{
  /**
   * Returns the value of the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' reference.
   * @see #setReference(UserDefinedType)
   * @see org.emoflon.express.express.ExpressPackage#getReferenceAttribute_Reference()
   * @model
   * @generated
   */
  UserDefinedType getReference();

  /**
   * Sets the value of the '{@link org.emoflon.express.express.ReferenceAttribute#getReference <em>Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' reference.
   * @see #getReference()
   * @generated
   */
  void setReference(UserDefinedType value);

} // ReferenceAttribute
