/**
 * generated by Xtext 2.28.0
 */
package org.emoflon.express.express;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Schema Container</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.express.express.SchemaContainer#getSchemas <em>Schemas</em>}</li>
 * </ul>
 *
 * @see org.emoflon.express.express.ExpressPackage#getSchemaContainer()
 * @model
 * @generated
 */
public interface SchemaContainer extends EObject
{
  /**
   * Returns the value of the '<em><b>Schemas</b></em>' containment reference list.
   * The list contents are of type {@link org.emoflon.express.express.Schema}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schemas</em>' containment reference list.
   * @see org.emoflon.express.express.ExpressPackage#getSchemaContainer_Schemas()
   * @model containment="true"
   * @generated
   */
  EList<Schema> getSchemas();

} // SchemaContainer
