/**
 * generated by Xtext 2.28.0
 */
package org.emoflon.express.express;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.emoflon.express.express.ExpressPackage#getStringAttribute()
 * @model
 * @generated
 */
public interface StringAttribute extends Attribute
{
} // StringAttribute
