/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.express.express;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use From</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.express.express.UseFrom#getSchema <em>Schema</em>}</li>
 *   <li>{@link org.emoflon.express.express.UseFrom#getImportedEntities <em>Imported Entities</em>}</li>
 * </ul>
 *
 * @see org.emoflon.express.express.ExpressPackage#getUseFrom()
 * @model
 * @generated
 */
public interface UseFrom extends Declaration
{
  /**
   * Returns the value of the '<em><b>Schema</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schema</em>' reference.
   * @see #setSchema(Schema)
   * @see org.emoflon.express.express.ExpressPackage#getUseFrom_Schema()
   * @model
   * @generated
   */
  Schema getSchema();

  /**
   * Sets the value of the '{@link org.emoflon.express.express.UseFrom#getSchema <em>Schema</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schema</em>' reference.
   * @see #getSchema()
   * @generated
   */
  void setSchema(Schema value);

  /**
   * Returns the value of the '<em><b>Imported Entities</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imported Entities</em>' containment reference.
   * @see #setImportedEntities(ImportedEntityList)
   * @see org.emoflon.express.express.ExpressPackage#getUseFrom_ImportedEntities()
   * @model containment="true"
   * @generated
   */
  ImportedEntityList getImportedEntities();

  /**
   * Sets the value of the '{@link org.emoflon.express.express.UseFrom#getImportedEntities <em>Imported Entities</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imported Entities</em>' containment reference.
   * @see #getImportedEntities()
   * @generated
   */
  void setImportedEntities(ImportedEntityList value);

} // UseFrom
