<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ADELE_Components" nsURI="http://ADELE_Components" nsPrefix="ADELE_Components">
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true" eSuperTypes="KernelSpices.ecore#//SKComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueChildrenNames legalName legalChildren"/>
    </eAnnotations>
    <eOperations name="getMax" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getClassifier" eType="#//Component"/>
    <eOperations name="isType" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isImplementation" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isInstance" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isClassifier" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isSubcomponent" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementationName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featuresLock" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subcomponentsLock" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subcomponentRefinement"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baTransition" upperBound="-1"
        eType="ecore:EClass BA_relations.ecore#//BATransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventDataPortConnection"
        upperBound="-1" eType="ecore:EClass ADELE_Relations.ecore#//EventDataPortConnection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventPortConnection" upperBound="-1"
        eType="ecore:EClass ADELE_Relations.ecore#//EventPortConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPortConnection" upperBound="-1"
        eType="ecore:EClass ADELE_Relations.ecore#//DataPortConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataAccessConnection" upperBound="-1"
        eType="ecore:EClass ADELE_Relations.ecore#//DataAccessConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busAccessConnection" upperBound="-1"
        eType="ecore:EClass ADELE_Relations.ecore#//BusAccessConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subprogramAccessConnection"
        upperBound="-1" eType="ecore:EClass ADELE_Relations.ecore#//SubprogramAccessConnection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterConnection" upperBound="-1"
        eType="ecore:EClass ADELE_Relations.ecore#//ParameterConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subprogramGroupAccessConnection"
        upperBound="-1" eType="ecore:EClass ADELE_Relations.ecore#//SubprogramGroupAccessConnection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractFeatureConnection"
        upperBound="-1" eType="ecore:EClass ADELE_Relations.ecore#//AbstractFeatureConnection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureGroupConnection"
        upperBound="-1" eType="ecore:EClass ADELE_Relations.ecore#//FeatureGroupConnection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRefines" upperBound="-1"
        eType="#//Component" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedSubcomponent" eType="#//Component"
        resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the subcomponent of the any component extended by the parent component only if this subcomponent is refined. Otherwise, return null."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRealFeatures" upperBound="-1"
        eType="ecore:EClass KernelSpices.ecore#//SKFeature" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRealChildrenComponents"
        upperBound="-1" eType="ecore:EClass KernelSpices.ecore#//SKComponent" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalComponent" eType="#//Component"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRelations" upperBound="-1"
        eType="ecore:EClass ADELE_Relations.ecore#//Relation" changeable="false" volatile="true"
        transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRealRelations" upperBound="-1"
        eType="ecore:EClass ADELE_Relations.ecore#//Relation" changeable="false" volatile="true"
        transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allOriginalRelations" upperBound="-1"
        eType="ecore:EClass ADELE_Relations.ecore#//Relation" changeable="false" volatile="true"
        transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subcomponentType" eType="#//Component"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bus" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Memory" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Processor" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Subprogram" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Thread" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThreadGroup" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubprogramGroup" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abstract" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualProcessor" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualBus" eSuperTypes="#//Component"/>
</ecore:EPackage>
