<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ADELE_Features" nsURI="http://ADELE_Features" nsPrefix="ADELE_Features">
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true" eSuperTypes="KernelSpices.ecore#//SKFeature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueFeatureNames legalName componentNotNull"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" eType="ecore:EClass KernelSpices.ecore#//SKComponent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refinement" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" defaultValueLiteral="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedFeature" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalFeature" eType="#//Feature"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Access" abstract="true" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//AccessDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectedFeature" abstract="true" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//PortDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusAccess" eSuperTypes="#//Access"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataAccess" eSuperTypes="#//Access"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubprogramAccess" eSuperTypes="#//Access"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubprogramGroupAccess" eSuperTypes="#//Access"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//DirectedFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureGroup" eSuperTypes="#//DirectedFeature KernelSpices.ecore#//SKComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="consistentDirections"/>
    </eAnnotations>
    <eOperations name="isInverse" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="feature" lowerBound="1" eType="#//Feature"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inverseFeature" eType="#//FeatureGroup"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRealFeatures" upperBound="-1"
        eType="#//Feature" changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventPort" eSuperTypes="#//DirectedFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataPort" eSuperTypes="#//DirectedFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventDataPort" eSuperTypes="#//DirectedFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFeature" eSuperTypes="#//DirectedFeature"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PortDirection">
    <eLiterals name="in"/>
    <eLiterals name="out" value="1"/>
    <eLiterals name="inout" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessDirection">
    <eLiterals name="provided" literal="provided"/>
    <eLiterals name="required" value="1"/>
  </eClassifiers>
</ecore:EPackage>
