<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ADELE_Relations" nsURI="http://ADELE_Relations" nsPrefix="ADELE_Relations">
  <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true" eSuperTypes="KernelSpices.ecore#//SKRelation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noSubcomponentFeatureOfFeatureGroupConnectionEnd"/>
    </eAnnotations>
    <eOperations name="getMax" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalSourceFeature"
        eType="ecore:EClass ADELE_Features.ecore#//Feature" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalSinkFeature" eType="ecore:EClass ADELE_Features.ecore#//Feature"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalSourceSubcomponent"
        eType="ecore:EClass ADELE_Components.ecore#//Component" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalSinkSubcomponent"
        eType="ecore:EClass ADELE_Components.ecore#//Component" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass KernelSpices.ecore#//SKObject" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sink" lowerBound="1" eType="ecore:EClass KernelSpices.ecore#//SKObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningComponent" lowerBound="1"
        eType="ecore:EClass ADELE_Components.ecore#//Component" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalRelation" eType="#//Relation"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessConnection" abstract="true" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectedFeatureConnection" abstract="true"
      eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusAccessConnection" eSuperTypes="#//AccessConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataAccessConnection" eSuperTypes="#//AccessConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubprogramAccessConnection" eSuperTypes="#//AccessConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubprogramGroupAccessConnection" eSuperTypes="#//AccessConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventPortConnection" eSuperTypes="#//DirectedFeatureConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataPortConnection" eSuperTypes="#//DirectedFeatureConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventDataPortConnection" eSuperTypes="#//DirectedFeatureConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterConnection" eSuperTypes="#//DirectedFeatureConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFeatureConnection" eSuperTypes="#//DirectedFeatureConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureGroupConnection" eSuperTypes="#//DirectedFeatureConnection"/>
</ecore:EPackage>
