<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="KernelSpices" nsURI="http://KernelSpices" nsPrefix="KernelSpices">
  <eClassifiers xsi:type="ecore:EClass" name="SKObject" abstract="true">
    <eOperations name="validateName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SKHierarchicalObject" abstract="true"
      eSuperTypes="#//SKObject">
    <eOperations name="addChild">
      <eParameters name="p_child" eType="#//SKHierarchicalObject"/>
    </eOperations>
    <eOperations name="isRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getNamedChild" eType="#//SKHierarchicalObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="I return my fist direct child with name=p_name"/>
      </eAnnotations>
      <eParameters name="p_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getNamedChildren">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="I return all my direct children with name=p_name"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="#//SKHierarchicalObject"/>
      </eGenericType>
      <eParameters name="p_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findLeveledChildren">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="I return all my children with level=p_level"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="#//SKHierarchicalObject"/>
      </eGenericType>
      <eParameters name="p_level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="isODSection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isComponent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isRelation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="verify" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="p_keyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="isTerminal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="addProperty" lowerBound="1">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addProperty" lowerBound="1">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="setProperty" lowerBound="1">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getProperty" lowerBound="1" eType="#//SKProperty">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Par convention, un SKHierarchicalObject dont le parent=null (pas de parent) a un leve=0."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//SKProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//SKHierarchicalObject"
        eOpposite="#//SKHierarchicalObject/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//SKHierarchicalObject" containment="true" eOpposite="#//SKHierarchicalObject/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="odSystems" upperBound="-1"
        eType="ecore:EClass ObjectDescriptionModel.ecore#//SKODSystem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SKComponent" eSuperTypes="#//SKHierarchicalObject">
    <eOperations name="getNamedFeature" eType="#//SKFeature">
      <eParameters name="p_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//SKFeature" containment="true" eOpposite="#//SKFeature/component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorizedSubcomponents"
        transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="#//SKComponent"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorizedFeatures" transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="#//SKComponent"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SKFeature" eSuperTypes="#//SKHierarchicalObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="#//SKFeatureVisibility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="#//SKComponent"
        eOpposite="#//SKComponent/features"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SKFeatureVisibility">
    <eLiterals name="Provided"/>
    <eLiterals name="Internal" value="1" literal="Internal"/>
    <eLiterals name="Required" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SKRelation" eSuperTypes="#//SKHierarchicalObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" lowerBound="2"
        upperBound="2" eType="#//SKObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SKProperty" eSuperTypes="#//SKHierarchicalObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
</ecore:EPackage>
