<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BlockCodeAdapter" nsURI="platform:/resource/BlockCodeAdapter/model/BlockCodeAdapter.ecore"
    nsPrefix="BlockCodeAdapter">
  <eClassifiers xsi:type="ecore:EClass" name="NodeToSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/BlockLanguage/model/BlockLanguage.ecore#//Specification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/BlockLanguage/model/BlockLanguage.ecore#//Block"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToWire">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/BlockLanguage/model/BlockLanguage.ecore#//Wire"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/BlockLanguage/model/BlockLanguage.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileToSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/MocaTree/model/MocaTree.ecore#//File"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/BlockLanguage/model/BlockLanguage.ecore#//Specification"/>
  </eClassifiers>
</ecore:EPackage>
