<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="glossarDocumentation" nsURI="platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore"
    nsPrefix="GlossarDocumentation">
  <eClassifiers xsi:type="ecore:EClass" name="Document">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//Entry" containment="true" eOpposite="#//Entry/document"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hyperRefs" upperBound="-1"
        eType="#//Document" eOpposite="#//Document/reverseHRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//DocumentationContainer"
        eOpposite="#//DocumentationContainer/documents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reverseHRef" upperBound="-1"
        eType="#//Document" eOpposite="#//Document/hyperRefs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Glossar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//GlossarEntry" containment="true" eOpposite="#//GlossarEntry/glossar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//DocumentationContainer"
        eOpposite="#//DocumentationContainer/glossar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlossarEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="glossar" eType="#//Glossar"
        eOpposite="#//Glossar/entries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//Entry" eOpposite="#//Entry/glossarentries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EntryType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="glossarentries" upperBound="-1"
        eType="#//GlossarEntry" eOpposite="#//GlossarEntry/entries"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" eType="#//Document"
        eOpposite="#//Document/entries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EntryType">
    <eLiterals name="FIELD"/>
    <eLiterals name="METHOD" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentationContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="documents" upperBound="-1"
        eType="#//Document" containment="true" eOpposite="#//Document/container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="glossar" lowerBound="1"
        eType="#//Glossar" containment="true" eOpposite="#//Glossar/container"/>
  </eClassifiers>
</ecore:EPackage>
