<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FamiliesToPersons_V0" nsURI="platform:/resource/FamiliesToPersons_V0/model/FamiliesToPersons_V0.ecore"
    nsPrefix="FamiliesToPersons_V0">
  <eClassifiers xsi:type="ecore:EClass" name="RegisterToRegister">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/SimpleFamilies/model/SimpleFamilies.ecore#//FamilyRegister"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/SimplePersons/model/SimplePersons.ecore#//PersonRegister"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyMemberToPerson">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/SimpleFamilies/model/SimpleFamilies.ecore#//FamilyMember"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/SimplePersons/model/SimplePersons.ecore#//Person"/>
  </eClassifiers>
</ecore:EPackage>
