<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Express2UML" nsURI="platform:/resource/Express2UML/model/Express2UML.ecore"
    nsPrefix="Express2UML">
  <eClassifiers xsi:type="ecore:EClass" name="Schema2Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity2Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function2SingleMethodClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationType2Enum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//EnumerationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Enumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationValue2EnumerationValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//EnumerationValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//EnumerationValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassAttribute2Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumAttribute2Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerTypeAttribute2IntegerAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//IntegerType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanTypeAttribute2BooleanAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//BooleanType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealTypeAttribute2RealAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//RealType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Real"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringTypeAttribute2StringAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//StringType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanAttribute2BooleanAttribute__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__aSrc" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__bt" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//BooleanType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__b" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__bt2b" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//BooleanTypeAttribute2BooleanAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2c" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Entity2Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassAttribute2Association__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__attr" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e1" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e2" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__udtr" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//UserDefinedTypeReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__c1" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__c2" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__ca2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//ClassAttribute2Association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2c1" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Entity2Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2c2" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Entity2Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity2Class__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__s" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__e2c" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Entity2Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__s2p" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Schema2Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumAttribute2Association__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__attr" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__enumSrc"
        lowerBound="1" eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//EnumerationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__udr" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//UserDefinedTypeReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__enumTrg"
        lowerBound="1" eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Enumeration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2c" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Entity2Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2e" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//EnumerationType2Enum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__ea2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//EnumAttribute2Association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationType2Enum__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__et" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//EnumerationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__s" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Enumeration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__et2e" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//EnumerationType2Enum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__s2p" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Schema2Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationTypeValues2EnumValues__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__et" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//EnumerationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__evSrc" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//EnumerationValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__s" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Enumeration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__evTrg" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//EnumerationValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__et2e" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//EnumerationType2Enum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__ev2ev" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//EnumerationValue2EnumerationValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__s2p" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Schema2Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function2SingleMethodClass__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__f" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__s" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__m" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__f2smc" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Function2SingleMethodClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__s2p" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Schema2Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerAttribute2IntegerAttribute__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__aSrc" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__it" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//IntegerType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__i" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2c" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Entity2Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__it2i" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//IntegerTypeAttribute2IntegerAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealAttribute2RealAttribute__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__aSrc" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__rt" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//RealType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__r" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Real"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2c" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Entity2Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__rt2r" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//RealTypeAttribute2RealAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema2Package__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__s" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__s2p" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Schema2Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringAttribute2StringAttribute__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__aSrc" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__st" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.emoflon.express/model/generated/Express.ecore#//StringType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__s" lowerBound="1"
        eType="ecore:EClass platform:/resource/UML/model/UML.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2c" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//Entity2Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__st2s" lowerBound="1"
        eType="ecore:EClass platform:/resource/Express2UML/model/Express2UML.ecore#//StringTypeAttribute2StringAttribute"/>
  </eClassifiers>
</ecore:EPackage>
