<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Clazz2GlossarDoc" nsURI="platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore"
    nsPrefix="Clazz2GlossarDoc">
  <eClassifiers xsi:type="ecore:EClass" name="Container2container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//ClazzContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//DocumentationContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clazz2doc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Clazz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Document"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field2entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Field"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Entry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method2entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Entry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter2entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Entry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clazz2DocRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__cCont" lowerBound="1"
        eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//ClazzContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__clazz" lowerBound="1"
        eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Clazz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__dCont" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//DocumentationContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__doc" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Document"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__c2d" lowerBound="1"
        eType="ecore:EClass platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore#//Clazz2doc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__cont2cont"
        lowerBound="1" eType="ecore:EClass platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore#//Container2container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container2ContainerRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__cCont" lowerBound="1"
        eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//ClazzContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__dCont" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//DocumentationContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__glossar" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Glossar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__c2d" lowerBound="1"
        eType="ecore:EClass platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore#//Container2container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field2EntityRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__clazz" lowerBound="1"
        eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Clazz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__field" lowerBound="1"
        eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Field"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__doc" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Document"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__entry" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Entry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2d" lowerBound="1"
        eType="ecore:EClass platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore#//Clazz2doc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__f2e" lowerBound="1"
        eType="ecore:EClass platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore#//Field2entry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlossarEntryRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__entry" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//GlossarEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__glossar"
        lowerBound="1" eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Glossar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlossarLinkRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__entry" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Entry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__gEntry" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//GlossarEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InheritanceRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__subClazz"
        lowerBound="1" eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Clazz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__superClazz"
        lowerBound="1" eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Clazz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__dCont" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//DocumentationContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__subDoc" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Document"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__superDoc"
        lowerBound="1" eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Document"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__sub2sub"
        lowerBound="1" eType="ecore:EClass platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore#//Clazz2doc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__super2super"
        lowerBound="1" eType="ecore:EClass platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore#//Clazz2doc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method2EntityRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__clazz" lowerBound="1"
        eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Clazz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__method" lowerBound="1"
        eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__doc" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Document"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__entry" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Entry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2d" lowerBound="1"
        eType="ecore:EClass platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore#//Clazz2doc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__f2e" lowerBound="1"
        eType="ecore:EClass platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore#//Method2entry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__method" lowerBound="1"
        eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__param" lowerBound="1"
        eType="ecore:EClass platform:/resource/SimpleClassInheritance/model/simpleClassInheritance.ecore#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__entry" lowerBound="1"
        eType="ecore:EClass platform:/resource/GlossarDocumentation/model/glossarDocumentation.ecore#//Entry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__m2e" lowerBound="1"
        eType="ecore:EClass platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore#//Method2entry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__p2e" lowerBound="1"
        eType="ecore:EClass platform:/resource/Clazz2GlossarDoc/model/Clazz2GlossarDoc.ecore#//Parameter2entry"/>
  </eClassifiers>
</ecore:EPackage>
