<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Adele" nsURI="platform:/resource/Adele/model/Adele.ecore" nsPrefix="Adele">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TODO: Add documentation for Blup"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Access" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRealFeatures" upperBound="-1"
        eType="#//Access" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" upperBound="-1" eType="#//Component"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRealChildrenComponents"
        upperBound="-1" eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refines" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedSubcomponent" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRealRelations" upperBound="-1"
        eType="#//AccessConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featuresDf" upperBound="-1"
        eType="#//DirectedFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRealFeaturesDf" upperBound="-1"
        eType="#//DirectedFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRealRelationsDfc" upperBound="-1"
        eType="#//DirectedFeatureConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRealFeaturesFg" upperBound="-1"
        eType="#//FeatureGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Access">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directionView" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedFeature" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalSinkSubcomponent"
        upperBound="-1" eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalSourceSubcomponent"
        upperBound="-1" eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalSourceFeature"
        upperBound="-1" eType="#//Access" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orginialSinkFeature" upperBound="-1"
        eType="#//Access" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//FeatureGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenC" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectedFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedFeature" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" upperBound="-1"
        eType="#//SKComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifierFg" upperBound="-1"
        eType="#//FeatureGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SKComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectedFeatureConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalSourceFeature"
        upperBound="-1" eType="#//DirectedFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalSinkFeature" upperBound="-1"
        eType="#//DirectedFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRealFeatures" upperBound="-1"
        eType="#//DirectedFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" upperBound="-1"
        eType="#//FeatureGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inverseFeature" upperBound="-1"
        eType="#//FeatureGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Access" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featuresDf" upperBound="-1"
        eType="#//DirectedFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedFeature" upperBound="-1"
        eType="#//FeatureGroup" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
