<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ba_components" nsURI="http://ba_components/1.0" nsPrefix="ba_components">
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorAnnex" eSuperTypes="#//BAComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="BAState" eSuperTypes="#//BAComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//BAStateKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BAComponent" abstract="true" eSuperTypes="KernelSpices.ecore#//SKComponent"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BAStateKind">
    <eLiterals name="none" value="7" literal="none"/>
    <eLiterals name="initial"/>
    <eLiterals name="complete" value="1"/>
    <eLiterals name="final" value="2"/>
    <eLiterals name="initial_final" value="3"/>
    <eLiterals name="initial_complete" value="4"/>
    <eLiterals name="initial_complete_final" value="5"/>
    <eLiterals name="complete_final" value="6"/>
  </eClassifiers>
</ecore:EPackage>
