<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SimpleChemistry" nsURI="platform:/resource/SimpleChemistry/model/SimpleChemistry.ecore"
    nsPrefix="SimpleChemistry">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TODO: Add documentation for SimpleChemistry. Hint: You may copy this element in the Ecore editor to add documentation to EClasses, EOperations, ..."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="H" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" eType="#//Atom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="O" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="2"
        eType="#//Atom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atoms" upperBound="-1"
        eType="#//Atom" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
