<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Aadl" nsURI="platform:/resource/Aadl/model/AadlComponent.ecore"
    nsPrefix="AadlComponent">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TODO: Add documentation for Blup"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFeature" upperBound="-1"
        eType="#//Access" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" upperBound="-1"
        eType="#//Access" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFeatureDF" upperBound="-1"
        eType="#//DirectedFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberDF" upperBound="-1"
        eType="#//DirectedFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberFG" upperBound="-1"
        eType="#//FeatureGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Access">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refined" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureClassifierFc" upperBound="-1"
        eType="#//FeatureClassifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureClassifier" upperBound="-1"
        eType="#//ComponentType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featClassifierDst" upperBound="-1"
        eType="#//DataSubcomponentType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionEnd" upperBound="-1"
        eType="#//Access" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionEndAce" upperBound="-1"
        eType="#//AccessConnectionEnd" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" upperBound="-1"
        eType="#//Subcomponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionEndDf" upperBound="-1"
        eType="#//DirectedFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextFg" upperBound="-1"
        eType="#//FeatureGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentImplementation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" upperBound="-1"
        eType="#//AccessConnectionEnd" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" upperBound="-1" eType="#//ComponentType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAccessConnection"
        upperBound="-1" eType="#//AccessConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberSub" upperBound="-1"
        eType="#//Subcomponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSubcomponent" upperBound="-1"
        eType="#//Subcomponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRealization" upperBound="-1"
        eType="#//Realization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedExtension" upperBound="-1"
        eType="#//ImplementationExtension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedExtensionTe" upperBound="-1"
        eType="#//TypeExtension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConnection" upperBound="-1"
        eType="#//Connection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="#//ConnectedElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" upperBound="-1"
        eType="#//ConnectedElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessConnectionEnd"/>
  <eClassifiers xsi:type="ecore:EClass" name="Subcomponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refined" upperBound="-1"
        eType="#//Subcomponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subCompType" upperBound="-1"
        eType="#//SubcomponentType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subComponentTypeCi" upperBound="-1"
        eType="#//ComponentImplementation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentImplementation"
        upperBound="-1" eType="#//ComponentImplementation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedClassifier" upperBound="-1"
        eType="#//ComponentType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedClassifierCi" upperBound="-1"
        eType="#//ComponentImplementation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Realization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implemented" upperBound="-1"
        eType="#//ComponentType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementationExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extended" upperBound="-1"
        eType="#//ComponentImplementation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicPackageSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedClassifier" upperBound="-1"
        eType="#//ComponentType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedClassfr" upperBound="-1"
        eType="#//FeatureGroupType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extended" upperBound="-1"
        eType="#//ComponentType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubcomponentType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectedFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refined" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" upperBound="-1"
        eType="#//Classifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifierFgt" upperBound="-1"
        eType="#//FeatureGroupType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="#//ConnectedElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" upperBound="-1"
        eType="#//ConnectedElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureGroupType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" upperBound="-1"
        eType="#//DirectedFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inverse" upperBound="-1"
        eType="#//FeatureGroupType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFeature" upperBound="-1"
        eType="#//Access" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFeatureDf" upperBound="-1"
        eType="#//DirectedFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedExtension" upperBound="-1"
        eType="#//GroupExtension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureType" upperBound="-1"
        eType="#//FeatureGroupType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSubcomponentType"/>
  <eClassifiers xsi:type="ecore:EClass" name="GroupExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extended" upperBound="-1"
        eType="#//FeatureGroupType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdlPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPublicSection" upperBound="-1"
        eType="#//PublicPackageSection" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
